name: The EARs Reviewing bot on approved changes

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved-changes:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'ERGA-BGE')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Thanks the reviewer for the approval
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # have to change this for forked repos
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REVIEWER: ${{ github.event.review.user.login }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --approve
