name: The EARs Reviewing bot on approved comments

on:
  workflow_run:
    workflows: [The EARs Reviewing bot on approved changes]
    types:
      - completed

jobs:
  approved-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: ./pr/pr_status

      - run: |
          source review-data.txt
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          echo "REVIEWER=${REVIEWER}" >> $GITHUB_ENV
          echo "SHOULD_RUN=${SHOULD_RUN}" >> $GITHUB_ENV

      - name: Set up Python
        if: ${{ env.SHOULD_RUN == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Thanks the reviewer for the approval
        if: ${{ env.SHOULD_RUN == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          REVIEWER: ${{ env.REVIEWER }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --approve
