name: The EARs Reviewing bot on approved changes

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved-changes:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'ERGA-BGE')
    runs-on: ubuntu-latest
    env:
      SUPERVISOR_PATH: supervisor.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Get supervisor name
        id: get_supervisor
        run: |
          SUPERVISOR=$(cat ear_bot/${{ env.SUPERVISOR_PATH }})
          echo "supervisor=$SUPERVISOR" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: github.event.review.user.login != steps.get_supervisor.outputs.supervisor
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Remove reviewer from the busy reviewers
        if: github.event.review.user.login != steps.get_supervisor.outputs.supervisor
        env:
          ARTIFACT_PATH: artifact.json
          REVIEWER: ${{ github.event.review.user.login }}
          SUPERVISOR: ${{ steps.get_supervisor.outputs.supervisor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWERS_PATH: reviewers.txt
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --remove

      - name: Uplaod artifact.json
        if: github.event.review.user.login != steps.get_supervisor.outputs.supervisor
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "ear_bot/artifact.json"
