name: The EARs Reviewing

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  pdf_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check for PDF files
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.pdf')" ]; then
              echo "PDF file found"
          else
              echo "No PDF file found"
              exit 0
          fi

  add_label_and_reviewer:
    needs: pdf_check
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ERGA-BGE"]
            });
      - name: Add reviewer and assignee
        uses: kentaro-m/auto-assign-action@v2.0.0
        addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - reviewerA
  - reviewerB
  - reviewerC