name: The EARs Reviewing bot on approved changes

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved-changes:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'ERGA-BGE')
    runs-on: ubuntu-latest
    env:
      SUPERVISOR_PATH: supervisor.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get supervisor name
        id: get_supervisor
        run: |
          SUPERVISOR=$(cat ear_bot/${{ env.SUPERVISOR_PATH }})
          echo "supervisor=$SUPERVISOR" >> $GITHUB_OUTPUT

      - name: Create comment for supervisor and reviewer
        if: github.event.review.user.login != steps.get_supervisor.outputs.supervisor
        uses: actions/github-script@v7
        with:
          script: |
            const message = `Thanks @${{ github.event.review.user.login }} for the review. I will add a new reviewed species for you to the table when @${{ steps.get_supervisor.outputs.supervisor }} approves and merges the PR. After merging, you can upload the assembly to ENA.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Remove reviewer from the busy reviewers
        env:
          ARTIFACT_PATH: artifact.json
          REVIEWER: ${{ github.event.review.user.login }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --remove

      - name: Uplaod artifact.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "ear_bot/artifact.json"
