name: The EARs Reviewing bot on approved comments

on:
  workflow_run:
    workflows: [The EARs Reviewing bot on approved changes]
    types:
      - completed

jobs:
  approved-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr_status
          path: pr_status.zip

      - name: Download artifact and extract the data
        run: |
          unzip pr_status.zip

          PR_NUMBER=$(grep PR_NUMBER pr_status | cut -d'=' -f2)
          REVIEWER=$(grep REVIEWER pr_status | cut -d'=' -f2)
          SHOULD_RUN=$(grep SHOULD_RUN pr_status | cut -d'=' -f2)

          echo "::set-env name=PR_NUMBER::${PR_NUMBER}"
          echo "::set-env name=REVIEWER::${REVIEWER}"
          echo "::set-env name=SHOULD_RUN::${SHOULD_RUN}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: ${{ env.SHOULD_RUN == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Thanks the reviewer for the approval
        if: ${{ env.SHOULD_RUN == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          REVIEWER: ${{ env.REVIEWER }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --approve
