name: The EARs Reviewing bot for PRs

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    paths:
      - "**.pdf"

jobs:
  add-label-and-supervisor:
    runs-on: ubuntu-latest
    env:
      SUPERVISOR_PATH: supervisor.txt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add label, supervisor and comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ERGA-BGE"]
            });

            const fs = require('fs');
            const supervisorContent = fs.readFileSync('${{ github.workspace }}/ear_bot/${{ env.SUPERVISOR_PATH }}', 'utf8');
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [supervisorContent]
            });

            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: [supervisorContent]
            });

            const researcher = context.payload.pull_request.user.login;
            const message = `👋 Hi @${researcher}, thanks for sending the EAR.\nI added the corresponding tag to the PR and appointed @${supervisorContent} as the assignee to supervise.`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
