name: The EARs Reviewing

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  pdf_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check for PDF files
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.pdf')" ]; then
              echo "PDF file found"
          else
              echo "No PDF file found"
              exit 1
          fi

  add_label_and_reviewer:
    needs: pdf_check
    runs-on: ubuntu-latest
    env:
      SUPERVISOR: brilliantarash
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["ERGA-BGE"]
            });
        
      - name: Add Supervisor
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              assignees: ["${{ env.SUPERVISOR }}"]
            });
            });
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ["${{ env.SUPERVISOR }}"]
            });


      - name: Create comment
        uses: actions/github-script@v7
        with:
          script: |
            const researcher = context.payload.pull_request.user.login;
            const message = "👋 Hi @${researcher}, thanks for sending the EAR of Valencia hispanica.\nI added the corresponding tag to the PR and appointed @${{ env.SUPERVISOR }} as the assignee to supervise.\nI will contact a reviewer ASAP.";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
            const reviewer = 'Reviewer'; // Random name
            const currentDate = new Date();
            const deadline = new Date(currentDate.getTime() + (7 * 24 * 60 * 60 * 1000)); // 7 days from the current date
            const deadlineFormatted = deadline.toLocaleString('en-US', { timeZone: 'CET' });
            const message = "👋 Hi @${reviewer}, do you agree to review this assembly?\n\nPlease reply to this message only with Yes or No by ${deadlineFormatted}.";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Create Artifact
        env:
          REVIEWER: ${{ env.SUPERVISOR }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          DATE: ${{ github.run_id }}
        run: |
          echo '{"reviewer": "${{ env.REVIEWER }}", "pr_number": "${{ env.PR_NUMBER }}", "date": "${{ env.DATE }}"}' > artifact.json
        

      - name: Uplaod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.json
