name: The EARs Reviewing bot on approved comments

on:
  workflow_run:
    workflows: [The EARs Reviewing bot on approved changes]
    types:
      - completed

jobs:
  approved-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact and extract the data
        run: |
          artifact_id=$(curl -sS -X GET \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
          | jq -r '.artifacts[] | select(.name == "pr_status") | .id')
          curl -sS -X GET \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -o pr_status.zip \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip"

          unzip pr_status.zip

          PR_NUMBER=$(grep PR_NUMBER pr_status | cut -d'=' -f2)
          REVIEWER=$(grep REVIEWER pr_status | cut -d'=' -f2)
          SHOULD_RUN=$(grep SHOULD_RUN pr_status | cut -d'=' -f2)

          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          echo "REVIEWER=${REVIEWER}" >> $GITHUB_ENV
          echo "SHOULD_RUN=${SHOULD_RUN}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: ${{ env.SHOULD_RUN == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Thanks the reviewer for the approval
        if: ${{ env.SHOULD_RUN == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          REVIEWER: ${{ env.REVIEWER }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ear_bot/requirements.txt
          python -u ear_bot/ear_bot_reviewer.py --approve
